server:
  port: 8080

spring:
  application:
    name: test-easyjava
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    codec:
      max-in-memory-size: 50MB
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_chat
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # 开发阶段自动建表；上线时改为 validate
    show-sql: true # 启动时，Hibernate 会将执行的 SQL 语句打印到控制台（日志）。
    properties:
      hibernate:
        format_sql: true  # 格式化sql
        dialect: org.hibernate.dialect.PostgreSQLDialect #  指定PostgreSQL方言

  # Spring AI 配置（通义千问兼容模式）
  ai:
    openai:
      api-key: sk-b7fbdd371bc247548f1fc31057fe5713
      base-url: https://dashscope.aliyuncs.com/compatible-mode  # 不包含 /v1，Spring AI 会自动添加
      chat:
        options:
          model: qwen1.5-110b-chat  # 通义千问模型
          temperature: 0.7
      embedding:
        options:
          model: text-embedding-v2

#    # DashScope（通义千问）配置
#    dashscope:
#      api-key: ${DASHSCOPE_API_KEY}  # 从环境变量读取
#      model: qwen1.5-110b-chat
app:
  upload:
    dir: uploads